apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: okd-coreos-prod
spec:
  params:
  - name: repo
    default: "https://github.com/openshift/os.git"
  - name: branch
    default: "master"
  - name: variant
    default: "okd-c9s"
  - name: version
    default: "4.13"
  - name: release-stream
    default: "stable"
  - name: target-registry
    default: "quay.io/okd"
  - name: baseos-container-image-name
    default: "centos-stream-coreos-9"
  - name: extensions-container-image-name
    default: "centos-stream-coreos-9-extensions"
  - name: upload-container-images
    default: "true"
  - name: tag-latest
    default: "false"
  - name: upload-bootimages
    default: "true"
  - name: s3-bucket-name
    default: "okd-scos"
  - name: s3-endpoint-url
    default: "https://okd-scos.s3.amazonaws.com/"
  - name: s3-aws-config-file
    default: "credentials"
  - name: notify-matrix
    default: "true"
  - name: matrix-room
    default: "!nStsazaBvZCZQHPWTY:fedoraproject.org"
  - name: matrix-endpoint
    default: 'matrix.org'
  - name: claimname
    default: 'pipeline-scos-4.13-pvc'
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: okd-coreos-$(tt.params.version)-prod-pipelinerun-
      annotations:
        operator.tekton.dev/prune.skip: "false"
        operator.tekton.dev/prune.resources: "taskrun, pipelinerun"
        operator.tekton.dev/prune.keep: "1"
        operator.tekton.dev/prune.strategy: "keep"
    spec:
      serviceAccountName: pipeline
      params:
        - name: repo
          value: $(tt.params.repo)
        - name: branch
          value: $(tt.params.branch)
        - name: variant
          value: $(tt.params.variant)   
        - name: version
          value: $(tt.params.version)
        - name: release-stream
          value: $(tt.params.release-stream)
        - name: target-registry
          value: $(tt.params.target-registry)
        - name: baseos-container-image-name
          value: $(tt.params.baseos-container-image-name)
        - name: extensions-container-image-name
          value: $(tt.params.extensions-container-image-name)
        - name: upload-container-images
          value: $(tt.params.upload-container-images)
        - name: tag-latest
          value: $(tt.params.tag-latest)
        - name: upload-bootimages
          value: $(tt.params.upload-bootimages)
        - name: s3-bucket-name
          value: $(tt.params.s3-bucket-name)
        - name: s3-endpoint-url
          value: $(tt.params.s3-endpoint-url)
        - name: s3-aws-config-file
          value: $(tt.params.s3-aws-config-file)
        - name: notify-matrix
          value: $(tt.params.notify-matrix)
        - name: matrix-room
          value: $(tt.params.matrix-room)
        - name: matrix-endpoint
          value: $(tt.params.matrix-endpoint)
        - name: claimname
          value: $(tt.params.claimname)
      pipelineRef:
        name: okd-coreos
      timeouts:
        pipeline: "4h0m0s"
      workspaces:
        - name: registry-credentials
          secret:
            secretName: okd-quay-pull-secret
        - name: s3-credentials
          secret:
            secretName: okd-s3-config
        - name: shared-workspace
          persistentVolumeClaim:
            claimName: $(tt.params.claimname)
