apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: okd-coreos
resources:
  - ../../base/batch/cronjobs/
  - ../../base/core/persistentvolumeclaims/
  - ../../base/core/persistentvolumes/
  - ../../base/storage.k8s.io/storageclasses/
  - ../../base/triggers.tekton.dev/eventlisteners/
  - ../../base/triggers.tekton.dev/triggerbindings/
  - ../../base/triggers.tekton.dev/triggertemplates/
