apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cosa-test
spec:
  steps:
    - image: 'quay.io/coreos-assembler/coreos-assembler:latest'
      name: build-and-test-qemu
      resources:
        limits:
          cpu: 2000m
          devices.kubevirt.io/kvm: '1'
          memory: 16Gi
        requests:
          cpu: 2000m
          devices.kubevirt.io/kvm: '1'
          memory: 16Gi
      script: |
        #!/usr/bin/env bash
        set -euxo pipefail

        cd /srv/coreos
        cosa buildextend-qemu
        #cosa kola run --parallel 2
  workspaces:
    - mountPath: /srv
      name: ws
