apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cosa-init
spec:
  params:
    - description: The manifest repo URL
      name: repo
      type: string
    - description: The manifest repo branch
      name: branch
      type: string
    - description: The CoreOS variant
      name: variant
      type: string
    - description: The OKD version
      name: version
      type: string
  steps:
    - image: 'quay.io/coreos-assembler/coreos-assembler:latest'
      imagePullPolicy: Always
      name: prepare-repo
      resources:
        limits:
          devices.kubevirt.io/kvm: '1'
          memory: 4Gi
        requests:
          devices.kubevirt.io/kvm: '1'
          memory: 4Gi
      script: |
        #!/usr/bin/env bash
        set -euxo pipefail

        mkdir -p /workspace/coreos
        cd /workspace/coreos

        cat << INFO
        Initializing coreos-assembler:

        Manifest repo:  $(params.repo)
        Branch:         $(params.branch)

        OKD version:    $(params.version)
        CoreOS variant: $(params.variant)

        INFO

        cosa init \
            --branch $(params.branch) \
            --variant $(params.variant) \
            $(params.repo)

        # Move rpms into scope of COSA VM
        if [ -d "/workspace/rpms" ]; then
          cp -r /workspace/rpms /workspace/coreos/
          createrepo_c /workspace/coreos/rpms
        fi

        # TODO: Upstream to openshift/os
        # Get oc and hypershift from the yum repo in the artifacts image,
        # instead of the rhel ose repo.
        sed -i 's/rhel-9.*-server-ose.*/artifacts/' $(readlink -f src/config/manifest-$(params.variant).yaml)
        cat <<EOF >> src/config/c9s.repo

        [artifacts]
        name=OKD RPM artifacts
        baseurl=file:///workspace/coreos/rpms/
        repo_gpgcheck=0
        gpgcheck=0
        enabled=1

        EOF

  workspaces:
    - mountPath: /workspace
      name: ws
