apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cosa-upload-s3
spec:
  params:
    - name: release-stream
      default: ""
      type: string
    - name: bucket-name
      default: ""
      type: string
    - name: endpoint-url
      default: ""
      type: string
    - name: aws-config-file
      default: "credentials"
      type: string
  steps:
    - image: 'quay.io/coreos-assembler/coreos-assembler:latest'
      imagePullPolicy: Always
      name: upload-image
      resources: {}
      script: |
        #!/usr/bin/env bash
        set -euxo pipefail

        cd /srv/coreos
        if [[ -z "$(params.endpoint-url)" || ! -f "$(workspaces.s3creds.path)/$(params.aws-config-file)" || -z "$(params.bucket-name)" ]]; then
          echo "Skipping upload to S3 - bucket params not set"
          exit 0
        fi
        cosa buildupload s3 \
          --endpoint-url=$(params.endpoint-url) \
          --aws-config-file=$(workspaces.s3creds.path)/$(params.aws-config-file) \
          --acl=bucket-owner-full-control \
           $(params.bucket-name)/$(params.release-stream)/builds

  workspaces:
    - name: s3creds
    - mountPath: /srv
      name: ws
