apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cosa-build-extensions
spec:
  params:
    - description: The CoreOS variant
      name: variant
      type: string
  steps:
    - image: 'quay.io/coreos-assembler/coreos-assembler:latest'
      imagePullPolicy: Always
      name: build-extensions-container
      resources:
        limits:
          cpu: 2000m
          devices.kubevirt.io/kvm: '1'
          memory: 12Gi
        requests:
          cpu: 2000m
          devices.kubevirt.io/kvm: '1'
          memory: 12Gi
      script: |
        #!/usr/bin/env bash
        set -euxo pipefail

        cd /srv/coreos

        # The rpms that were extracted from the rhel-9-server-ose-rpms repo
        # are not present inside the container used to build the
        # extensions, however `rpm-ostree compose extensions`
        # will try to fetch metadata for all repos listed in
        # both {manifest,extensions}.yaml
        # TODO: Find a more elegant way to do this
        sed -i 's/- rhel-9-server-ose-rpms//' $(readlink -f src/config/manifest-$(params.variant).yaml)

        # build with the CentOS image rather than the ubi image. Using the ubi image is acceptable as long as we don't
        # pull in RHEL content, but basing it on CentOS brings consistency with other images.
        sed -ri 's/registry.access.redhat.com\/ubi([0-9]+)\/ubi:latest/quay.io\/centos\/centos:stream\1/' $(readlink -f src/config/extensions/Dockerfile)

        cosa build-extensions-container
        printf "%s" "OK" > $(results.output.path)
  results:
    - name: output
  workspaces:
    - mountPath: /srv
      name: ws
